constants = {
    "reserved": [
        "auto",
        "else",
        "long",
        "switch",
        "break",
        "enum",
        "register",
        "typedef",
        "case",
        "extern",
        "return",
        "union",
        "char",
        "float",
        "short",
        "unsigned",
        "const",
        "for",
        "signed",
        "void",
        "continue",
        "goto",
        "sizeof",
        "volatile",
        "default",
        "if",
        "static",
        "while",
        "do",
        "int",
        "struct",
        "_Packed",
        "double",
    ],
    "dataTypes": ["int", "char", "double", "float"],
    "functionDataTypes": ["int", "char", "double", "float", "void"],
    "functionDeclaratioDatatypes": ["int", "char", "double", "float", "return"],
}
